### Introduction

Notebook contains set of the exercises realated to ***Linear Algebra Basics Tutorial***.   
First we will load necessary Python modules, and then we will proceed with exercises:


In [55]:
import numpy as np
import timeit

### Exercise, matrix transpose:

Transpose of a matrix is an operator which flips a matrix over its diagonal, switching the row and column indices of the 
matrix by producing another matrix denoted as AT.

Create matrix with 5 rows and 3 columns, values should be initialized randomly. 
Apply transpose operator and check the new matrix. Apply transpose to new matrix again and resultng matrix will be the same as original matrix.

In [67]:
A = np.random.randint(10, size=(5, 3))

print(A.shape)
print(A)

B = A.T
print(B.shape)
print(B)

C = np.transpose(B)
print(C.shape)
print(C)

(5, 3)
[[4 7 9]
 [1 0 8]
 [0 3 7]
 [2 7 6]
 [4 8 1]]
(3, 5)
[[4 1 0 2 4]
 [7 0 3 7 8]
 [9 8 7 6 1]]
(5, 3)
[[4 7 9]
 [1 0 8]
 [0 3 7]
 [2 7 6]
 [4 8 1]]


### Exercise, broadcasting:

Possiblity to do operations on arrays of different sizes is called broadcasting.

What will be result of following code:

```
A = np.array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])
B = np.array([0, 1, 2])

print(A + B)
```


In [79]:
A = np.array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

B = np.array([0, 1, 2])

print(A + B)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


### Exercise, is matrix multiplication commutative: 

Create matrix with 3 rows and 2 columns, values should be initialized randomly. 
Check is matrix multiplication commutative. Use transpose for creation of the second matrix.

In mathematics, a binary operation is commutative if changing the order of the operands does not change the result.   
A X B = B X A

Note: use NumPy dot() product and transpose function.

In [50]:
A = np.random.randint(10, size=(3, 2))
B = A.T

print(A.shape)
print(B.shape)

print(A)
print(B)

C = np.dot(A, B)
D = np.dot(B, A)

print(C.shape)
print(D.shape)

print(C)
print(D)


(3, 2)
(2, 3)
[[3 4]
 [8 8]
 [6 5]]
[[3 8 6]
 [4 8 5]]
(3, 3)
(2, 2)
[[ 25  56  38]
 [ 56 128  88]
 [ 38  88  61]]
[[109 106]
 [106 105]]


### Exercise, is matrix multiplication associative: 

Create 3 matrices with 3 rows and 3 columns, values should be initialized randomly. 
Check is matrix multiplication associative. 

Within an expression containing two or more occurrences in a row of the same associative operator, the order in which the operations are performed does not matter as long as the sequence of the operands is not changed. 

A(B X C) = (A X B)C

Note: use NumPy dot() product and transpose function(for third matrix)

In [59]:
A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))
C = B.T

print(A.dot(B))
print(B.dot(A))

print(A.shape)
print(B.shape)
print(C.shape)

print(A.dot(B.dot(C)))
print(A.dot(B).dot(C))

[[ 45 162 144]
 [ 69 108  78]
 [ 18  81  63]]
[[108  54  63]
 [108  36 102]
 [135  54  72]]
(3, 3)
(3, 3)
(3, 3)
[[2556 1620 2889]
 [1656 1356 1881]
 [1206  756 1350]]
[[2556 1620 2889]
 [1656 1356 1881]
 [1206  756 1350]]


### Exercise, is matrix multiplication distributive: 

Create matrix with 3 rows and 2 columns, values should be initialized randomly. 
Check is matrix multiplication distributive. 

A(B + C) = (A X B) + (A X C)

Note: use NumPy dot() product and transpose function(for third matrix)

In [54]:
A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))
C = B.T

print(A.dot(B + C))
print(A.dot(B) + A.dot(C))

[[ 84 116 103]
 [134 117 115]
 [132  54  78]]
[[ 84 116 103]
 [134 117 115]
 [132  54  78]]


### Exercise, compare matrix multiplication speed:

Compare matrix-matrix multiplication speed by comparing pure Python matrix multiplication and NumPy matrix multiplication.

Notes: 

* size of the matrix should be defined as parameter
* matrix values should be initialized randomly
* collect current time with functions: ```start = timeit.default_timer()```
* pseudo code for pure Python matrix multiplication

```
resultPurePython = np.zeros((SIZE,SIZE))
for i in range(SIZE):
  for j in range(SIZE):
    for k in range(SIZE):
      resultPurePython[i,k] += A[i,j]*B[j,k]
      
```

Practice of replacing explicit loops with array expressions is commonly referred to as ***vectorization***.   
In general, vectorized array operations will often be one or two (or more) orders of magnitude faster than their pure Python equivalents.


In [71]:

# Set up the variables
SIZE = 50
A = np.random.rand(SIZE,SIZE)
B = np.random.rand(SIZE,SIZE)

# Try the naive way in Python
start = timeit.default_timer()

# --> Matrix multiplication in pure Python
resultPurePython = np.zeros((SIZE,SIZE))
for i in range(SIZE):
  for j in range(SIZE):
    for k in range(SIZE):
      resultPurePython[i,k] += A[i,j]*B[j,k]

time_spent = timeit.default_timer() - start
print(time_spent)

# Try using numpy
start = timeit.default_timer()

# --> Matrix multiplication in numpy
resultNumPy = A.dot(B)

time_spent = timeit.default_timer() - start
print(time_spent)

0.10420954739220178
0.00028681526782747824
