#### Linear Algebra


Linear algebra is a form of mathematics, which is basis for many Machine Learning algorithms, especially Deep Learning algorithms.
Many computer scientists have little or no experience with it, even a good understanding of linear algebra is essential for understanding and working in the field of the Machine and Deep Learning.

The conceptes behind Liner Algebra give you better intuition for how algorithms really work under the hood, which enables you to make better decisions. 

It is a relatively young field of study, having initially been formalized in the 1800s in order
to find unknowns in systems of linear equations. Linear Algebra is a continuous form of mathematics and is applied throughout science and engineering. Linear Algebra is also central to almost all areas of mathematics like geometry and functional analysis. 

Therefore Linear Algebra is used in many domains like:

* Graphs and Networks, analyzing networks.
* Markov Matrices, Population, and Economics, population growth
* Linear Programming, the simplex optimization method
* Fourier Series: Linear Algebra for functions, signal processing
* Statistics and probability, for example least squares for regression
* Computer Graphics, such as the translation, rescaling and rotation of images


In MachineLearning Linear Algebra is used as well. Some of the areas where Linear Algera is used are:

* Datasets


In Deep Learning Neural Networks, data is represented by linear equations, which are presented in the form of Linear Algebra objects like matrices and vectors
Algorithms which are used to train neural networks, consist of Linear Algreba operations, such as add, multiply, subtract, etc.

Linear algebra provides the first steps into vectorisation, presenting a deeper way of thinking about parallelisation of certain operations. 
Algorithms written in standard 'for-loop' notation can be reformulated as matrix equations providing significant gains in computational efficiency.

Such methods are used in the major Python libraries such as NumPy, SciPy, Scikit-Learn, Pandas and Tensorflow. 
GPUs have been designed to carry out optimised linear algebra operations. The explosive growth in Deep Learning can partially be attributed to the highly parallelised nature of the 
underlying algorithms on commodity GPU hardware.

The fundamental objects in Linear Algebra are 
* Scalars   
* Vectors   
* Matrices   
* Tensors

So, let's dig deeper in fundamental Linear Algebra objects

##### Scalars

Scalar is a single number. Scalar is example of a 0th-order tensor.   
Python built-in scalar types are int, float, complex, bytes, Unicode. 
In NumPy, there are 24 fundamental data types which are described in NumPy section.

We can declare two variables of type int and float using standard Python notation and check with NumPy are those variables scalars or not:


In [29]:
import numpy as np

x = 1.0
y = 1

print(np.isscalar(x))
print(np.isscalar(y))

True
True


##### Vectors

A vector is a one dimensional list or array of single numbers and are an example of 1st-order tensor. 
Vector is a matrix with a single column or a row. Vector has single index which points to specific value within the Vector.

We can declare vector in Python on a few ways:


In [7]:
x = np.arange(10)
print(x)

y = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(y)

z = [10, 20, 30]
print(z)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10, 20, 30]


Element of the vector can be accessed using index syntax:

In [8]:
print(x[1])
print(y[1])
print(z[1])


1
1
20


##### Matrices

Matrix is two dimensional array of numbers and is an example of 2nd-order tensors. 
Matrix has two indexes, first one points to the row and the second one to the column. 
A Matrix can have multiple numbers of rows and columns. 
Dimensions of a matrix is described in terms of rows and columns.


Vector is a Matrix as well, but with only one row or one column.

In Python, we use NumPy in order to create n-dimensional arrays. 
N-dimensional arrays are basically matrices, so we use matrix method and pass in the lists and thereby defining a matrix.


In [12]:
a = np.arange(9).reshape(3,3)

print(a)
print(a.shape)

b = np.array([
 [1,2,3], 
 [4,5,6]
])

print(b)
print(b.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)


Element of the matrix can be accessed using syntax:

In [13]:
firstMatrixElement = a[0][0]
print(firstMatrixElement)

print(b[0][1])


0
2


##### Tensors

Tensor is a multidimensional array of numbers, arranged on a regular grid, with a variable number of axes. 
A Tensor has three indexes, first one points to the row, the second to the column and the third one to the axis. 

Tensor is the most general term for all of these concepts above because a Tensor can be a Vector and a Matrix, 
depending on the number of indexes it has. 

In Python, we use NumPy in order to create n-dimensional arrays. 


In [14]:
t = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])

print(t)
print(t.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
(3, 3, 3)


Element of the tensor can be accessed as follows:

In [17]:
print(t[0])
print(t[0][0])
print(t[0][0][0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
1


##### Algebra

##### Vectors

###### Scalar operations on Vectors

Scalar operations involve a vector and a number(scalar). 
Vector can be modified by adding, subtracting, or multiplying the number from all the values in the vector.


In [19]:
a = np.array([1,2,3])

print(a)
print(a.shape)

print(10 + a) # output [11 12 13]
print(10 - a) # output [9 8 7]
print(10 * a) # output [10 20 30]

[1 2 3]
(3,)
[11 12 13]
[9 8 7]
[10 20 30]


###### Elementwise operations on Vectors

In elementwise operations like addition, subtraction, and division, values that correspond positionally are combined to produce a new vector. 
The 1st value in vector A is paired with the 1st value in vector B. The 2nd value is paired with the 2nd, and so on. 
This means the vectors must have equal dimensions to complete the operation


In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a)
print(b)

print(a + b) # output [5 7 9]
print(a - b) # output [-3 -3 -3]
print(a * b) # output [ 4 10 18]

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]


###### Dot product on Vectors

The dot product of two vectors is a scalar. 
Dot product of vectors and matrices (matrix multiplication) is one of the most important operations in Deep Learning.


In [21]:
a = np.array([1,2])
b = np.array([3,4])

print(np.dot(y,x)) # output a1*b1 + a2*b2 = 11

285


###### Hadamard product on Vectors

Hadamard Product is element wise multiplication and it outputs a vector.


In [22]:
a = np.array([1,2])
b = np.array([3,4])

print(a*b) # output [a1*b1 a2*b2] = [3 8]

[3 8]


##### Matrices

###### Scalar operations

Scalar operations with matrices works the same way as they do for vectors. 
Simply apply the scalar to every element in the matrix add, subtract, divide, multiply, etc.


In [24]:
a = np.array([[1,2,3], [4, 5, 6]])

print(a)
print(a.shape)

print(10 + a) # output [[11 12 13][14 15 16]]
print(10 - a) # output [[9 8 7] [6 5 4]]
print(10 * a) # output [[10 20 30] [40 50 60]]

[[1 2 3]
 [4 5 6]]
(2, 3)
[[11 12 13]
 [14 15 16]]
[[9 8 7]
 [6 5 4]]
[[10 20 30]
 [40 50 60]]



###### Elementwise operations

In order to add, subtract, or divide two matrices they must have equal dimensions.
We combine corresponding values in an elementwise fashion to produce a new matrix.

This operation is fairly easy but requires both matrices of same dimension to perform the operation. 
The resulting matrix is of the same dimension. We have to just add the each value of first matrix with the corresponding value of the other matrix.


In [25]:
a = np.array([
 [1, 2], 
 [3, 4]
])

b = np.array([
 [1, 2], 
 [3, 4]
])

print(a + b)  # output [[2 4] [6 8]]
print(a - b)  # output [[0 0] [0 0]]

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


###### Hadamard product

Hadamard product of matrices is an elementwise operation. Values that correspond positionally are multiplied to produce a new matrix.

In [26]:
a = np.array([
 [1, 2], 
 [3, 4]
])

b = np.array([
 [1, 2], 
 [3, 4]
])

print(a * b)  # output [[a1*b1 a2*b2] [a3*b3 a4*b4]] = [[1 4] [9 16]]

[[ 1  4]
 [ 9 16]]


###### Matrix multiplication

Matrix multiplication is based on rules for multiplying matrices together to produce a new matrix.
Not all matrices are eligible for multiplication. In addition, there is a requirement on the dimensions of the resulting matrix output. 

Rules:

 * The number of columns of the 1st matrix must equal the number of rows of the 2nd   
 * The product of an M x N matrix and an N x K matrix is an M x K matrix. The new matrix takes the rows of the 1st and columns of the 2nd matrices

Matrix multiplication relies on dot product to multiply various combinations of rows and columns. 


In [28]:
a = np.array([
 [1, 2], 
 [3, 4],
 [5, 6]
])

b = a.T # transpose, b = [[1 3 5] [2 4 6]]

print(a.shape)
print(b.shape)

c = np.dot(a, b)

print(c) # output 1st el. = a11*b11 + a12*b21 = 5, 2nd el. = a11*b12 + a12*b22 = 11, ... -> [[ 5 11 17] [11 25 39]  [17 39 61]]
print(c.shape)

(3, 2)
(2, 3)
[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
(3, 3)
