### Linear Algebra

#### Introduction

Linear algebra is a form of mathematics, which is basis for many Machine Learning algorithms, especially Deep Learning algorithms.
Many computer scientists have little or no experience with it, even a good understanding of linear algebra is essential for understanding and working in the field of the Machine and Deep Learning.

Linear Algebra is a relatively young field of study, having initially been formalized in the 1800s in order
to find unknowns in systems of linear equations. Linear Algebra is a continuous form of mathematics and is applied throughout science and engineering. Linear Algebra is also central to almost all areas of mathematics like geometry and functional analysis. 

Therefore Linear Algebra is used in many domains like:

* Graphs and Networks analysis 
* Population growth analysis
* Linear Programming, the simplex optimization method
* Fourier Series, signal processing
* Statistics and probability, least squares for regression
* Computer Graphics, such as the translation, rescaling and rotation of images


#### Linear Algebra in Machine Learning

Linear Algebra is foundation for the Machine Learning. Datasets, images, one hot encodings, deep learning algortihms are based on the principles of the Linear Algebra. Let's see some common examples: 

#### Datasets

In Machine Learning, it is common that model is build based on a dataset. Dataset is very often table with rows and columns, 
where each row represents an observation and column represents a feature of the observation. For example below is part of the
dataset from bank which contains historical behavior of the customers(customer churn prediction):

```
RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1,15634602,Hargrave,619,France,Female,42,2,0,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,159660.8,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.1,0
6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
```

As you can see, dataset is an matrix, which is key data structure in Linear Algebra. Last column shows information did customer leaved the bank or not, and we extract last column in separated dataset, we will have vector which is another important data structure in Linear Algebra.


#### Images

Image consist of a set of the pixels. For a grayscale image each pixel is a scalar value from 0 to 255. Image has widht and height, so grayscale image is represented as matrix. 
Color images has one matrix per color(Red, Green, Blue), so here we are talking about tensor with 3 dimension.

Operations on the image, such as cropping, scaling, shearing and so on are all described using the notation and operations of
linear algebra.


#### Encoding

As you can see above, not all data in dataset is numerical, some values can be defined as text, check above columns Geography and Gender. Gender column can be encoded as Label Encoder in classes 0 or 1. 

If we apply same approach for Geography column, countries will be defined as 0, 1, 2 etc. This is not right approach, therefore in such a cases we can use One Hot Encoder.

#### Linear Reggression

Linear regression is often used in machine learning for predicting numerical values in simpler
regression problems. The most common way of solving linear regression is via a least squares
optimization that is solved using matrix factorization methods from linear regression, such as
an LU decomposition or an singular-value decomposition or SVD.


#### PCA, SVD, ...

#### Recommendation systems

If you go to popular web sites like Amazon or Netflix and if you search for some items, site will recommend simira item based on yours previous activitie. The development of Recommendation systems is primarily is based on linear algebra methods. 

A simple example is in the calculation of the similarity between sparse customer behavior vectors using distance measures such as Euclidean distance or dot products. 

Matrix factorization methods like the singular-value decomposition are used widely in recommender systems to distill item and user data to their essence for querying and searching and comparison.


#### Deep Learning


In Deep Learning Neural Networks, data is represented by linear equations, which are presented in the form of Linear Algebra objects like matrices and vectors. Algorithms which are used to train neural networks, consist of Linear Algreba operations, such as add, multiply, subtract, etc.

Linear algebra provides the first steps into vectorisation, presenting a deeper way of thinking about parallelisation of certain operations. Algorithms written in standard 'for-loop' notation can be reformulated as matrix equations providing significant gains in computational efficiency.

Such methods are used in the major Python libraries such as NumPy, SciPy, Scikit-Learn, Pandas and Tensorflow. 
GPUs have been designed to carry out optimised linear algebra operations. The explosive growth in Deep Learning can partially be attributed to the highly parallelised nature of the 
underlying algorithms on commodity GPU hardware.

#### Fundamental objects of the Linear Algebra

The fundamental objects in Linear Algebra are 
* Scalars   
* Vectors   
* Matrices   
* Tensors

So, let's dig deeper in fundamental Linear Algebra objects

##### Scalars

Scalar is a single number. Scalar is example of a 0th-order tensor.   
Python built-in scalar types are int, float, complex, bytes, Unicode. 
In NumPy, there are 24 fundamental data types which are described in NumPy section.

We can declare two variables of type int and float using standard Python notation and check with NumPy are those variables scalars or not:


In [30]:
import numpy as np

x = 1.0
y = 1

print(np.isscalar(x))
print(np.isscalar(y))

True
True


##### Vectors

A vector is a one dimensional list or array of single numbers and is an example of 1st-order tensor. 
Vector is a matrix with a single column or a row. Vector has single index which points to specific value within the Vector.

We can declare vector in Python on a few ways:


In [31]:
x = np.arange(10)
print(x)

y = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(y)

z = [10, 20, 30]
print(z)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10, 20, 30]


Element of the vector can be accessed using index syntax:

In [32]:
print(x[1])
print(y[1])
print(z[1])


1
1
20


##### Matrices

Matrix is two dimensional array of numbers and is an example of 2nd-order tensors. 
Matrix has two indexes, first one points to the row and the second one to the column. 
A Matrix can have multiple numbers of rows and columns. 
Dimensions of a matrix is described in terms of rows and columns.


Vector is a Matrix as well, but with only one row or one column.

In Python, we use NumPy in order to create n-dimensional arrays. 
N-dimensional arrays are basically matrices, so we use matrix method and pass in the lists and thereby defining a matrix.


In [33]:
a = np.arange(9).reshape(3,3)

print(a)
print(a.shape)

b = np.array([
 [1,2,3], 
 [4,5,6]
])

print(b)
print(b.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)


Element of the matrix can be accessed using syntax:

In [34]:
firstMatrixElement = a[0][0]
print(firstMatrixElement)

print(b[0][1])


0
2


##### Tensors

Tensor is a multidimensional array of numbers, arranged on a regular grid, with a variable number of axes. 
A Tensor has three indexes, first one points to the row, the second to the column and the third one to the axis. 

Tensor is the most general term for all of mentioned concepts, because a Tensor can be a Vector and a Matrix, 
depending on the number of indexes it has. 

In Python, we use NumPy in order to create n-dimensional arrays. 


In [35]:
t = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])

print(t)
print(t.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
(3, 3, 3)


Element of the tensor can be accessed as follows:

In [36]:
print(t[0])
print(t[0][0])
print(t[0][0][0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
1


#### Vectors Arithmetic

##### Scalar operations on Vectors

Scalar operations involve a vector and a number(scalar). 
Vector can be modified by adding, subtracting, or multiplying the number(scalar) from all the values in the vector.

The multiplication is prefomed on each element of the vector to result in a new scaled vector of same length.

***c = s X v***

Now if we have vector with 3 elements:
...

result will be:   

***c = (s X v1, s X v2, s X v3)***

or on another way:   

***c[0] = v[0] X s***   
***c[1] = v[1] X s***   
***c[2] = v[2] X s***   

Same rule is used for addition, substraction and division.

Let's se example with NumPy:

In [37]:
a = np.array([1,2,3])

print(a)
print(a.shape)

print(10 + a) # output [11 12 13]
print(10 - a) # output [9 8 7]
print(10 * a) # output [10 20 30]
print(30 / a) # output [30. 15. 10]

print(a + 10) # output [11 12 13]
print(a - 10) # output [-9 -8 -7]
print(a * 10) # output [10 20 30]

print(a / 30) # output [0.0333. 0.066 0.1]

[1 2 3]
(3,)
[11 12 13]
[9 8 7]
[10 20 30]
[30. 15. 10.]
[11 12 13]
[-9 -8 -7]
[10 20 30]
[0.03333333 0.06666667 0.1       ]


##### Elementwise operations on Vectors

In elementwise operations like addition, subtraction, and division, values that correspond positionally are combined to produce a new vector. 
The 1st value in vector A is paired with the 1st value in vector B. The 2nd value is paired with the 2nd, and so on. 
This means the vectors must have equal dimensions to complete the operation.

###### Vector Addition

Two vectors can be added to create new third vector:

***c = a + b***

New vector has same shape like other two vectors, result will be:   

***c = (a1 + b1, a2 + b2, a3 + b3)***

or on another way:   

***c[0] = a[0] + b[0]***   
***c[1] = a[1] + b[1]***   
***c[2] = a[2] + b[2]***   

Example:

In [38]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a, b, a + b) # output [5 7 9]


[1 2 3] [4 5 6] [5 7 9]


###### Vector Subtraction

One vector can be subtracted from another of equal shape to create new third vector:

***c = a - b***

New vector has same shape like other two vectors, result will be:   

***c = (a1 - b1, a2 - b2, a3 - b3)***

or on another way:   

***c[0] = a[0] - b[0]***   
***c[1] = a[1] - b[1]***   
***c[2] = a[2] - b[2]***   

Example:

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a, b, a - b) # output [-3 -3 -3]

[1 2 3] [4 5 6] [-3 -3 -3]


###### Vector Multiplication

Two vectors of equal shape can be multiplied(Hadamard product) together:

***c = a X b***

New vector has same shape like other two vectors, result will be:   

***c = (a1 X b1, a2 X b2, a3 X b3)***

or on another way:   

***c[0] = a[0] X b[0]***   
***c[1] = a[1] X b[1]***   
***c[2] = a[2] X b[2]***   

Example:

In [40]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a, b, a * b) # output [4 10 18]

[1 2 3] [4 5 6] [ 4 10 18]


###### Vector Division

Two vectors of equal shape can be divided:

***c = a / b***

New vector has same shape like other two vectors, result will be:   

***c = (a1 / b1, a2 / b2, a3 / b3)***

or on another way:   

***c[0] = a[0] / b[0]***   
***c[1] = a[1] / b[1]***   
***c[2] = a[2] / b[2]***   

Example:

In [41]:
a = np.array([1,2,3])
b = np.array([1,2,3])

print(a, b, a / b) # output [1. 1. 1.]

[1 2 3] [1 2 3] [1. 1. 1.]




###### Dot product on Vectors

The dot product of two vectors is a scalar. It is sum of the the multiplied elements of two vectors of the same shape.
Dot product of vectors and matrices (matrix multiplication) is one of the most important operations in Deep Learning.

***c = a . b***

New vector has same shape like other two vectors, result will be:   

***c = (a1 X b1 + a2 X b2 + a3 X b3)***

or on another way:   

***c[0] = a[0] X b[0] + a[1] X b[1] + a[2] X b[2]***   

Example:

In [42]:
a = np.array([1,2])
b = np.array([3,4])

print(np.dot(a,b)) # output a1*b1 + a2*b2 = 11

11


#### Matrices Arithmetic

##### Scalar operations

Scalar operations with matrices works the same way as they do for vectors. 
Simply apply the scalar to every element in the matrix add, subtract, divide, multiply, etc.

The multiplication is prefomed on each element of the matri. The result is scaled matrix of the same shape as parent matrix.

***C = Av***

Now if we have matrix with 3 rows and 2 columns, result will be:   


***C[0, 0] = A[0, 0] X b***   
***C[1, 0] = A[1, 0] X b***   
***C[2, 0] = A[2, 0] X b***   
***C[0, 1] = A[0, 1] X b***   
***C[1, 1] = A[1, 1] X b***   
***C[2, 1] = A[2, 1] X b***   

Same rule is used for addition, substraction and division.

Let's see example with NumPy:

In [43]:
a = np.array([[1,2,3], [4, 5, 6]])

print(a)
print(a.shape)

print(10 + a) # output [[11 12 13][14 15 16]]
print(10 - a) # output [[9 8 7] [6 5 4]]
print(10 * a) # output [[10 20 30] [40 50 60]]
print(10 / a) # output [[10. 5. 3.33] [2.5 2. 1.66]]

[[1 2 3]
 [4 5 6]]
(2, 3)
[[11 12 13]
 [14 15 16]]
[[9 8 7]
 [6 5 4]]
[[10 20 30]
 [40 50 60]]
[[10.          5.          3.33333333]
 [ 2.5         2.          1.66666667]]



##### Elementwise operations

In order to add, subtract, or divide two matrices they must have equal dimensions.
We combine corresponding values in an elementwise fashion to produce a new matrix.

This operation is fairly easy but requires both matrices of same dimension to perform the operation. 
The resulting matrix is of the same dimension. We have to just add the each value of first matrix with the corresponding value of the other matrix.

###### Matrix Addition

Two matrix can be added to create new third vector:

***C = A + B***

New matrix has same shape like other two matices, result will be:   

***C[0, 0] = A[0, 0] + B[0, 0]***   
***C[1, 0] = A[1, 0] + B[1, 0]***   
***C[2, 0] = A[2, 0] + B[2, 0]***   
***C[0, 1] = A[0, 1] + B[0, 1]***   
***C[1, 1] = A[1, 1] + B[1, 1]***   
***C[2, 1] = A[2, 1] + B[2, 1]***   

Example:


In [44]:
A = np.array([[1,2],[3, 4]])
B = np.array([[1,2],[3, 4]])

print(A + B)  # output [[2 4],[6 8]]

[[2 4]
 [6 8]]


###### Matrix Subtraction

One matrix can be subtracted with another:

***C = A - B***

New matrix has same shape like other two matices, result will be:   

***C[0, 0] = A[0, 0] - B[0, 0]***   
***C[1, 0] = A[1, 0] - B[1, 0]***   
***C[2, 0] = A[2, 0] - B[2, 0]***   
***C[0, 1] = A[0, 1] - B[0, 1]***   
***C[1, 1] = A[1, 1] - B[1, 1]***   
***C[2, 1] = A[2, 1] - B[2, 1]***   

Example:


In [45]:
A = np.array([[1,2],[3, 4]])
B = np.array([[1,2],[3, 4]])

print(A - B)  # output [[0 0],[0 0]]

[[0 0]
 [0 0]]


###### Matrix Multiplication

Two matrices can be multiplied together, and this is often called Hadamard product:

***C = A o B***

New matrix has same shape like other two matices, result will be:   

***C[0, 0] = A[0, 0] X B[0, 0]***   
***C[1, 0] = A[1, 0] X B[1, 0]***   
***C[2, 0] = A[2, 0] X B[2, 0]***   
***C[0, 1] = A[0, 1] X B[0, 1]***   
***C[1, 1] = A[1, 1] X B[1, 1]***   
***C[2, 1] = A[2, 1] X B[2, 1]***   

Example:


In [46]:
A = np.array([[1,2],[3, 4]])
B = np.array([[1,2],[3, 4]])

print(A * B)  # output [[1 4],[9 16]]

[[ 1  4]
 [ 9 16]]


###### Matrix Division

Matrix can be divided by another matrix with same dimension:

***C = A / B***

New matrix has same shape like other two matices, result will be:   

***C[0, 0] = A[0, 0] / B[0, 0]***   
***C[1, 0] = A[1, 0] / B[1, 0]***   
***C[2, 0] = A[2, 0] / B[2, 0]***   
***C[0, 1] = A[0, 1] / B[0, 1]***   
***C[1, 1] = A[1, 1] / B[1, 1]***   
***C[2, 1] = A[2, 1] / B[2, 1]***   

Example:


In [47]:
A = np.array([[1,2],[3, 4]])
B = np.array([[1,2],[3, 4]])

print(A / B)  # output [[1. 1.],[1. 1.]]

[[1. 1.]
 [1. 1.]]


###### Matrix Multiplication

Matrix multiplication is based on rules for multiplying matrices together to produce a new matrix.
Not all matrices are eligible for multiplication. In addition, there is a requirement on the dimensions of the resulting matrix output. 

Rules:

 * The number of columns of the 1st matrix must be equal as number of rows of the 2nd matix   
 * The product of an M x N matrix and an N x K matrix is an M x K matrix. The new matrix takes the rows of the 1st and columns of the 2nd matrices

The intuition for the matrix multiplication is that we are calculating the dot product between each row in matrix A with each column in matrix B.
Matrix multiplication can be described using array notation:

***C[0, 0] = A[0, 0] X B[0, 0] + A[0, 1] X B[1, 0]***   
***C[1, 0] = A[1, 0] X B[0, 0] + A[1, 1] X B[1, 0]***   
***C[2, 0] = A[2, 0] X B[0, 0] + A[2, 1] X B[1, 0]***   
***C[0, 1] = A[0, 1] X B[0, 1] + A[0, 1] X B[1, 1]***   
***C[1, 1] = A[1, 1] X B[0, 1] + A[1, 1] X B[1, 1]***   
***C[2, 1] = A[2, 1] X B[0, 1] + A[2, 1] X B[1, 1]***   


Example with NumPy:

In [48]:
a = np.array([
 [1, 2], 
 [3, 4],
 [5, 6]
])

b = a.T # transpose, b = [[1 3 5] [2 4 6]]

print(a.shape)
print(b.shape)

c = np.dot(a, b)

print(c) # output 1st el. = a11*b11 + a12*b21 = 5, 2nd el. = a11*b12 + a12*b22 = 11, ... -> [[ 5 11 17] [11 25 39]  [17 39 61]]
print(c.shape)

(3, 2)
(2, 3)
[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
(3, 3)


##### Matrix-Vector Multiplication

Matrix and vector can be multiplied together as long as rule for the matrix multiplication is satisfied. Number of columns in the 
matrix must be equal to the number fo items in vector.

***c = Av***

Multiplication can be described using array notation:   


***c[0] = A[0, 0] X v[0] + A[0, 1] X v[0]***   
***c[1] = A[1, 0] X v[0] + A[1, 1] X v[1]***   
***c[2] = A[2, 0] X v[0] + A[2, 1] X v[1]***   

Let's see example:

In [49]:
a = np.array([
 [1, 2], 
 [3, 4],
 [5, 6]
])

b = np.array([1, 2])

print(a.shape)
print(b.shape)

c = np.dot(a, b)

print(c) # output [ 5 11 17] 

(3, 2)
(2,)
[ 5 11 17]


#### Tensor Arithmetic

We can perfom element-wise arithmetic between tensors.

##### Tensor Addition

Element-wise addition of two tensors with the same dimensions results in the new temsor with same dimensions.


***C = A + B***

Now if we have two tensors with shape (2, 2, 2), result will be:   


***C[0, 0, 0] = A[0, 0, 0] + B[0, 0, 0]***   
***C[0, 0, 1] = A[0, 0, 1] + B[0, 0, 0]***   

***C[0, 1, 0] = A[0, 1, 0] + B[0, 1, 0]***   
***C[0, 0, 1] = A[0, 0, 1] + B[0, 0, 1]***   

***C[1, 0, 0] = A[1, 0, 0] + B[1, 0, 0]***   
***C[1, 0, 1] = A[1, 0, 1] + B[1, 0, 1]***   

***C[1, 1, 0] = A[1, 1, 0] + B[1, 1, 0]***   
***C[1, 1, 1] = A[1, 1, 1] + B[1, 1, 1]***   


Let's see example with NumPy:

In [67]:
A = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

B = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

print(A.shape)

C = A + B
print(C)

(2, 2, 2)
[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


##### Tensor Subtraction

Element-wise subtraction of two tensors with the same dimensions results in the new temsor with same dimensions.


***C = A - B***

Now if we have two tensors with shape (2, 2, 2), result will be:   


***C[0, 0, 0] = A[0, 0, 0] - B[0, 0, 0]***   
***C[0, 0, 1] = A[0, 0, 1] - B[0, 0, 0]***   

***C[0, 1, 0] = A[0, 1, 0] - B[0, 1, 0]***   
***C[0, 0, 1] = A[0, 0, 1] - B[0, 0, 1]***   

***C[1, 0, 0] = A[1, 0, 0] - B[1, 0, 0]***   
***C[1, 0, 1] = A[1, 0, 1] - B[1, 0, 1]***   

***C[1, 1, 0] = A[1, 1, 0] - B[1, 1, 0]***   
***C[1, 1, 1] = A[1, 1, 1] - B[1, 1, 1]***   


Let's see example with NumPy:

In [68]:
A = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

B = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

print(A.shape)

C = A - B
print(C)

(2, 2, 2)
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


##### Tensor Multiplication

Element-wise multiplication of two tensors with the same dimensions results in the new temsor with same dimensions.
Operation is called Hadamard product.


***C = A o B***

Now if we have two tensors with shape (2, 2, 2), result will be:   


***C[0, 0, 0] = A[0, 0, 0] o B[0, 0, 0]***   
***C[0, 0, 1] = A[0, 0, 1] o B[0, 0, 0]***   

***C[0, 1, 0] = A[0, 1, 0] o B[0, 1, 0]***   
***C[0, 0, 1] = A[0, 0, 1] o B[0, 0, 1]***   

***C[1, 0, 0] = A[1, 0, 0] o B[1, 0, 0]***   
***C[1, 0, 1] = A[1, 0, 1] o B[1, 0, 1]***   

***C[1, 1, 0] = A[1, 1, 0] o B[1, 1, 0]***   
***C[1, 1, 1] = A[1, 1, 1] o B[1, 1, 1]***   


Let's see example with NumPy:

In [69]:
A = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

B = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

print(A.shape)

C = A * B
print(C)

(2, 2, 2)
[[[ 1  4]
  [ 9 16]]

 [[25 36]
  [49 64]]]


##### Tensor Division

Element-wise division of two tensors with the same dimensions results in the new temsor with same dimensions.

***C = A / B***

Now if we have two tensors with shape (2, 2, 2), result will be:   


***C[0, 0, 0] = A[0, 0, 0] / B[0, 0, 0]***   
***C[0, 0, 1] = A[0, 0, 1] / B[0, 0, 0]***   

***C[0, 1, 0] = A[0, 1, 0] / B[0, 1, 0]***   
***C[0, 0, 1] = A[0, 0, 1] / B[0, 0, 1]***   

***C[1, 0, 0] = A[1, 0, 0] / B[1, 0, 0]***   
***C[1, 0, 1] = A[1, 0, 1] / B[1, 0, 1]***   

***C[1, 1, 0] = A[1, 1, 0] / B[1, 1, 0]***   
***C[1, 1, 1] = A[1, 1, 1] / B[1, 1, 1]***   


Let's see example with NumPy:

In [70]:
A = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

B = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

print(A.shape)

C = A / B
print(C)

(2, 2, 2)
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


##### Tensor Product

....

***C = A / B***

Now if we have two tensors with shape (2, 2, 2), result will be:   
???


***C[0, 0, 0] = A[0, 0, 0] / B[0, 0, 0]***   
***C[0, 0, 1] = A[0, 0, 1] / B[0, 0, 0]***   

***C[0, 1, 0] = A[0, 1, 0] / B[0, 1, 0]***   
***C[0, 0, 1] = A[0, 0, 1] / B[0, 0, 1]***   

***C[1, 0, 0] = A[1, 0, 0] / B[1, 0, 0]***   
***C[1, 0, 1] = A[1, 0, 1] / B[1, 0, 1]***   

***C[1, 1, 0] = A[1, 1, 0] / B[1, 1, 0]***   
***C[1, 1, 1] = A[1, 1, 1] / B[1, 1, 1]***   


Let's see example with NumPy:

In [80]:
A = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

B = np.array([ 
    [[1,2], [3, 4]], 
    [[5,6], [7, 8]]]) 

print(A.shape)

C = np.tensordot(A, B, axes = 3) # test various axes 0, 1, 2, 3 ???????
print(C.shape)
print(C)

(2, 2, 2)
()
204


We passed basics of Linear Algebra. In advances lecture we will talk about vector norms, types of matrices, matix decomposition, 
eigen decomposotion, singular value decomposition, principal component analysis.